[versions]
aboutLibraries = "13.2.1"
kotlin = "2.3.0"
material3 = "1.4.0"

[libraries]
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
